config/routes.rb
Rails.application.routes.draw do
  get 'upvote/:post_id' => 'votes#upvote', as: :upvote

  get 'downvote/:post_id' => 'votes#downvote', as: :downvote

  devise_for :users
  root to: 'posts#index'
  
  get 'posts/index'

  get 'posts/show'

  get 'posts/new'

  get 'posts/create'

  get 'posts/update'

  get 'users/index'

  get 'users/show'

  resources :users
  resources :posts
  resources :sports
  resources :teams

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # belongs_to :user
  belongs_to :sport
  belongs_to :team

  belongs_to :user
  has_many :favorites
  has_many :user_favorites, through: :favorites, source: :user

  # before_save :set_votes #setting attributes when making a new
  
  def upvote
    self.upvotes += 1
  end 

  def downvote
    self.downvotes +=1
  end

  def total
    self.upvotes + self.downvotes
  end

private

  # def set_votes
  #   self.upvotes = 0
  #   self.downvotes = 0
  # end



end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :teams
  has_many :posts
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :posts
  belongs_to :sport
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :post

  # @upvotes_list = []
  # @downvotes_list = []
  # @teams_list = []

  # def add_upvote(post)
  #   @upvotes_list << post
  # end

  # def add_downvote

  # end

  # def add_team

  # end

  # def remove_team

  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
 
    if @post.update(post_params.merge(user: current_user))
      redirect_to @post
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Post Deleted'
  end



# update from Brooks
  # def create
  #   @post = Post.find(params[:id])
 
  #   if @post.update(post_params.merge(user: current_user))
  #     redirect_to @post
  #   else
  #     render :new
  #   end
  # end

  # original create
  #   @post = Post.new(post_params)

  #   if @post.save
  #     redirect_to @post
  #   else
  #     render :new
  #   end

private

  def post_params
    params.require(:post).permit(:body, :upvotes, :downvotes, :user_id, :sport_id, :team_id)
  end



end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sport = Sport.all
  end

  def show
    @sport = Sport.find(params[:id])
  end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @team = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  # def create
  #   @user = User.new(user_params)
 
  #   if @user.update(user_params)
  #     redirect_to @user
  #   else
  #     render :new
  #   end
  # end


private

  def user_params
    params.require(:user).permit(:username, :email, post_ids: [])
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  # end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def upvote
    post = Post.find(params[:post_id])
    post.upvote
    post.save
    current_user.favorite_posts << post
    redirect_to root_path
  end

  def downvote
    post = Post.find(params[:post_id])
    post.downvote
    post.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<style>

h1 {
  text-align: center;
}


body {
  background-color: #00b6e3;
}

.body {
  font-family: helvetica;
  font-size: 24px;
  font-weight: 100;
  padding-top: 2px;
  padding-bottom: 2px;
}

.username {
  font-size: 16px;
  font-weight: bolder;
}

.tag {
  font-size: 14px;
  font-weight: 300;
}

.newpost {
  font-size: 20px;
  position: fixed;
  top: 9%;
  right: 15%;
}

.timestamp {
  font-size: 12px;
  font-style: italic;
}

.navbar-default {
  position: fixed;
}

li ul li {
  display: none;
}

li:hover ul li {
  display: block;
  font-size: 14px;
}

li ul li {
  display: none;
}

li:hover ul li {
  display: block;
  font-size: 14px;
}

ul li ul li {
  display: none;
}

ul li ul li {
  display: none;
  font-size: 40px;
}

</style>


<head>
  <title>CrowdWave</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container">

  <!-- Static navbar -->
  <div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'NFL', sport_path(1) %></li>
          <li class="active"><%= link_to 'NBA', sport_path(2)  %></li>
          <li class="active"><%= link_to 'MLB', sport_path(3)  %></li>
        </ul>

        <div class="navbar-text navbar-right">
         <% if user_signed_in? %> 
            <%= link_to 'Profile', user_path(current_user) %> &nbsp | &nbsp
            <%= link_to 'Edit Account', edit_user_path(current_user) %>  &nbsp | &nbsp
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path %>
          <% end %>
        </div>
<!--         <li class="navbar-text navbar-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-toggle" role="menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>  
        </ul>
      </li> -->
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </div>

  <%- if notice %>
    <div class="alert alert-info"><%= notice %></div>
  <%- end %>
  <%- if alert %>
    <div class="alert alert-warning"><%= alert %></div>
  <%- end %>

  <%= yield %>
  <br>

</div> <!-- /container -->

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <div class="input-group"> 
    <%= f.input :body %>
  </div> <br>

  <div class="input-group"> 
    <%= f.association :sport, label_method: :name, prompt: "Select Sport" %>
  </div> <br>

  <div class="input-group"> 
    <%= f.association :team, label_method: :team_name, prompt: "Select Team" %>
  </div> <br>


  <div class="input-group">
    <% @post.user_id = current_user.id %>
  </div> <br>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Most Recent Posts</h1>

<h3>
  <% if user_signed_in? %>
    <div class="newpost"> <%= link_to "New Post", posts_new_path(@post) %> </div>
  <% end %>
</h3>
<hr>



<p>
<% @post.reverse.each do |post| %>
  <div class="username"> 
    <%= link_to "#{post.user.username}", user_path(post.user) if post.user %> <!-- post.user.username-->
    <% if post.sport %>
      | <%= link_to "#{post.sport.name}", sport_path(post.sport) if post.sport %> 
    <% end %> <% if post.team %>
      | <%= link_to "#{post.team.team_name}", team_path(post.team) if post.team %> 
    <% end %> </div>
  <div class="body"> <%= post.body if post.body %> </div>
  <div class="timestamp"> <%= post.updated_at %> </div>
  Upvotes: <%= post.upvotes %> &nbsp &nbsp &nbsp
  Downvotes: <%= post.downvotes %> </br> 

  <%= link_to "Upvote It!", upvote_path(post_id: post.id), class: 'btn btn-primary' %>
  <%= link_to "Downvote It!", downvote_path(post_id: post.id), class: 'btn btn-primary' %> <br>



  <%= link_to "View Post and Comments", posts_show_path(@post, :id => post.id) %>
  <% if post.user == current_user %>
    | <%= link_to "Edit Post", edit_post_path(@post, :id => post.id) %> |
    <%= link_to 'Delete', post_path(@post, :id => post.id), method: :delete %><br>
  <% end %>
  <hr>
  </br>
<% end %>

</p>


</html>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1> Show The <%= params[:id] %>th Post </h1>

<p> 
 <div class="username"> 
    <%= link_to "#{@post.user.username}", user_path(@post.user) if @post.user %> <!-- post.user.username-->
    <% if @post.sport %>
      | <%= link_to "#{@post.sport.name}", sport_path(@post.sport) if @post.sport %> 
    <% end %> <% if @post.team %>
      | <%= link_to "#{@post.team.team_name}", team_path(@post.team) if @post.team %> 
    <% end %> </div>
 <div class="body"> <%= @post.body %> </div>
 <div class="timestamp"> <%= @post.updated_at %> </div>
 Upvotes: <%= @post.upvotes %> &nbsp &nbsp &nbsp
 Downvotes: <%= @post.downvotes %> </br> 
  <% if @post.user == current_user %>
  <%= link_to "Edit Post", edit_post_path(@post, :id => @post.id) %> |
  <%= link_to 'Delete', post_path(@post, :id => @post.id), method: :delete %><br>
<% end %>
</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/sports/show.html.erb
<h1> <%= @sport.name %> </h1>

<h3>
  <% if user_signed_in? %>
    <div class="newpost"> <%= link_to "New Post", posts_new_path(@post) %> </div>
  <% end %>
</h3>


<h4>
<% Team.all.each do |team| %>
  <% if team.sport == @sport %>
      <%= link_to "#{team.team_name}", team_path(team.id) if team.team_name %> &nbsp | &nbsp
  <% end %> 
<% end %>
</h4>

<hr>


<p> 
<% Post.all.reverse.each do |post| %>
  <% if post.sport == @sport %>
       <div class="username"> 
          <%= link_to "#{post.user.username}", user_path(post.user) if post.user %> <!-- post.user.username-->
          <% if post.sport %>
            | <%= link_to "#{post.sport.name}", sport_path(post.sport) %> 
          <% end %> <% if post.team %>
            | <%= link_to "#{post.team.team_name}", team_path(post.team) %> 
          <% end %> </div>    
      <div class="body"> <%= post.body if post.body %> </div>
      <div class="timestamp"> <%= post.updated_at %> </div>
      Upvotes: <%= post.upvotes %> &nbsp &nbsp &nbsp
      Downvotes: <%= post.downvotes %> </br> 
      <%= link_to "Upvote It!", upvote_path(post_id: post.id), class: 'btn btn-primary' %>
      <%= link_to "Downvote It!", downvote_path(post_id: post.id), class: 'btn btn-primary' %> <br>
      <%= link_to "View Post and Comments", posts_show_path(@post, :id => post.id) %>

      <% if post.user == current_user %>
        | <%= link_to "Edit Post", edit_post_path(@post, :id => post.id) %> |
        <%= link_to 'Delete', post_path(@post, :id => post.id), method: :delete %><br>
      <% end %>
      <hr>
      <br>
  <% end %>
<% end %>
</p>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :username, label_method: :username %> <br>
  <%= f.input :email, label_method: :email %> <br>


  <%= f.submit class: 'btn btn-primary' %>
  
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>This is where we show all the Users</h1>

<p>
<% @user.each do |user| %>
  <%= user.username %> </br> </br>
<% end %>

</p>

app/views/users/show.html.erb
<h1> <%= User.find(params[:id]).username %></h1>

<h2>
  <% if user_signed_in? %>
    <div class="newpost"><%= link_to "New Post", posts_new_path(@post) %> </div>
  <% end %>
</h2>

<p>
  <% @user.posts.reverse.each do |post| %>
  <div class="username"> 
    <%= link_to "#{post.user.username}", user_path(post.user) if post.user %> <!-- post.user.username-->
    | <%= link_to "#{post.sport.name}", sport_path(post.sport) if post.sport %> 
    | <%= link_to "#{post.team.team_name}", team_path(post.team) if post.team %> </div>
  <div class="body"> <%= post.body if post.body %> </div>
  <div class="timestamp"> <%= post.updated_at %> </div>
  Upvotes: <%= post.upvotes %> &nbsp &nbsp &nbsp
  Downvotes: <%= post.downvotes %> </br> 
   <%= link_to "Upvote It!", upvote_path(post_id: post.id), class: 'btn btn-primary' %>
  <%= link_to "Downvote It!", downvote_path(post_id: post.id), class: 'btn btn-primary' %> <br>
  
  <%= link_to "View Post and Comments", posts_show_path(@post, :id => post.id) %>
  <% if post.user == current_user %>
    | <%= link_to "Edit Post", edit_post_path(@post, :id => post.id) %> |
    <%= link_to 'Delete', post_path(@post, :id => post.id), method: :delete %><br>
  <% end %>
  <hr>
  </br>

<h1> Favorites </h1>

<hr>

  <% @user.favorite_posts.each do |favorite| %>
    <div class="username">
      <%= favorite.user.username %> </div>
    <div class="body">
      <%= favorite.body %> </div>
    <div class="timestamp"> <%= post.updated_at %> </div>
      Upvotes: <%= post.upvotes %> &nbsp &nbsp &nbsp
      Downvotes: <%= post.downvotes %> </br> 
    <% if user_signed_in? %>
      <%= link_to "Upvote It!", upvote_path(post_id: post.id), class: 'btn btn-primary' %>
      <%= link_to "Downvote It!", downvote_path(post_id: post.id), class: 'btn btn-primary' %> <br>
    <% end %>
  <% end %>
<% end %>


</p>

app/views/votes/downvote.html.erb
<h1>Votes#downvote</h1>
<p>Find me in app/views/votes/downvote.html.erb</p>

app/views/votes/upvote.html.erb
<h1>Votes#upvote</h1>
<p>Find me in app/views/votes/upvote.html.erb</p>